enabled: true

image:
  repository: postgres
  tag: 17.10-alpine3.23
  pullPolicy: IfNotPresent

auth:
  username: ghostrecon
  database: ghostrecon
  postgresPassword: ""
  password: ""

service:
  port: 5432

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 20Gi

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 70
  runAsGroup: 70
  fsGroup: 70
  fsGroupChangePolicy: OnRootMismatch
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

networkPolicy:
  enabled: true

terminationGracePeriodSeconds: 60
