apiVersion: v1
kind: ConfigMap
metadata:
  name: ghostrecon-config
  labels:
    {{- include "ghostrecon.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
