{{- if .Values.serviceAccount.create }}
{{- range $service := .Values.services }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $service }}
  labels:
    {{- include "ghostrecon.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $service }}
automountServiceAccountToken: false
---
{{- end }}
{{- range $worker := $.Values.workerQueues }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ghostrecon-worker-{{ $worker.name }}
  labels:
    {{- include "ghostrecon.labels" $ | nindent 4 }}
    app.kubernetes.io/component: worker-{{ $worker.name }}
automountServiceAccountToken: false
---
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ghostrecon-scheduler
  labels:
    {{- include "ghostrecon.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
automountServiceAccountToken: false
{{- end }}
